name: Scrape Latest
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"
jobs:
  scrape:
    name: Scrapes latest comics from ViewComics and adds them to database
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_SSL_CERT: cacert.pem
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.8"
          cache: "pip"
      - name: Install dependencies via Pip
        run: pip install -r requirements.txt
      - name: Run scraper
        run: scrapy crawl ViewComicsLatest
